#!/usr/bin/env bash
# Arch Linux Post-Install Script  (run from INSIDE chroot)

set -e

# -- Timezone and locale ------------------------------------------------------
ln -sf /usr/share/zoneinfo/Canada/Eastern /etc/localtime
hwclock --systohc

sed -i 's/^#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
sed -i 's/^#fr_CA.UTF-8/fr_CA.UTF-8/' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf

echo "KEYMAP=cf" > /etc/vconsole.conf

# -- Hostname -----------------------------------------------------------------
echo "nixilium" > /etc/hostname

# -- Boot + Network + Required Tools -----------------------------------------
pacman -S --noconfirm grub efibootmgr sudo networkmanager nano git base-devel
systemctl enable NetworkManager
systemctl start NetworkManager

grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg

# -- Root password ------------------------------------------------------------
echo "==> Set ROOT password"
passwd

# -- User + sudo --------------------------------------------------------------
useradd -m -G wheel,audio,video,network nixilium
echo "==> Set password for user nixilium"
passwd nixilium

echo 'nixilium ALL=(ALL:ALL) ALL' >> /etc/sudoers

# -- Desktop ------------------------------------------------------------------
pacman -S --noconfirm xfce4 xfce4-goodies lightdm lightdm-gtk-greeter firefox
systemctl enable lightdm

# -- Yay (AUR)
cd /tmp
git clone https://aur.archlinux.org/yay-bin.git
chown -R nixilium:nixilium yay-bin
su - nixilium -c "cd /tmp/yay-bin && makepkg -si --noconfirm"

# -- Themes + Apps
su - nixilium -c "
yay --noconfirm --answerdiff None --answerclean None -S arc-gtk-theme papirus-icon-theme
yay --noconfirm --answerdiff None --answerclean None -S steam discord spotify-launcher
"
"

echo '✅ Post-installation complete. Reboot and login as nixilium'
